export enum PartOfSpeech {
  NOUN = 'NOUN',
  VERB = 'VERB',
  ADJECTIVE = 'ADJECTIVE',
  ADVERB = 'ADVERB',
  PRONOUN = 'PRONOUN',
  DETERMINER = 'DETERMINER',
  PREPOSITION = 'PREPOSITION',
  CONJUNCTION = 'CONJUNCTION',
  PARTICLE = 'PARTICLE',
  INTERJECTION = 'INTERJECTION',
  NUMERAL = 'NUMERAL',
  PROPER_NOUN = 'PROPER_NOUN',
  OTHER = 'OTHER',
}
export const partOfSpeechLabel: Record<PartOfSpeech, string> = {
  [PartOfSpeech.NOUN]: 'נאָמען',
  [PartOfSpeech.VERB]: 'ווערב',
  [PartOfSpeech.ADJECTIVE]: 'אַדזשעקטיוו',
  [PartOfSpeech.ADVERB]: 'אַדווערב',
  [PartOfSpeech.PRONOUN]: 'פּראָנאָמען',
  [PartOfSpeech.DETERMINER]: 'דעטערמינער',
  [PartOfSpeech.PREPOSITION]: 'פּרעפּאָזיציע',
  [PartOfSpeech.CONJUNCTION]: 'קאָנדזשונקציע',
  [PartOfSpeech.PARTICLE]: 'פּאַרטיקל',
  [PartOfSpeech.INTERJECTION]: 'אינטערדזשעקשאַן',
  [PartOfSpeech.NUMERAL]: 'צאָלוואָרט',
  [PartOfSpeech.PROPER_NOUN]: 'אייגענער נאָמען',
  [PartOfSpeech.OTHER]: 'אַנדער',
};
